### PR TITLE
Add properties and replace

### PR DESCRIPTION
**Pull request by bouk**
@CamDavidsonPilon @kevincox

### CODE REVIEW

**Comment by kevincox** [comment]
+:100:

**Comment by kevincox** [comment]
Also could you please submit this upstream?

**Comment by bouk** [comment]
Created upstream PR here: https://github.com/intiocean/pyinter/pull/19

**Comment by CamDavidsonPilon** [comment]
And does this need to be bumped on the starscream side?

**Comment by kevincox** [comment]
Yeah, in the decencies you just need to change the SHA.

**Pull request merged**
